@host = http://localhost:3000
@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTY3MjMwNjR9.A8rEpXEMG-qXw0vkV1QEMEauqNxvqJi1c-s9hepihVg

#################### CAMPAIGNS #####################

### Campaigns Index
GET {{host}}/campaigns.json

### Campaigns Create
POST {{host}}/campaigns.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "user_id": "1",
  "name": "Definitely Not a Cursed Town",
  "description": "What? I already said - it's definitely not cursed."
}

### Campaign Show
GET {{host}}/campaigns/2.json

### Campaign Update
PATCH {{host}}/campaigns/3.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "Okay it's a cursed town",
  "description": "C'mon, don't blame me. If I told you it was cursed, you wouldn't have gone."
}

### Campaign Destroy
DELETE {{host}}/campaigns/4.json
Authorization: Bearer {{jwt}}

#################### CREATURES #####################

### Creatures Index
GET {{host}}/creatures.json

### Creatures Create
POST {{host}}/creatures.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "api_index": "goblin",
  "api_type": "humanoid",
  "name": "Goblin",
  "campaign_id": "3"
}

### Creatures Show
GET {{host}}/creatures/6.json

### Creatures Update
PATCH {{host}}/creatures/6.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "api_index": "gnoll",
  "name": "Gnoll"
}

### Creatures Destroy
DELETE {{host}}/creatures/6.json
Authorization: Bearer {{jwt}}

#################### NPCS ######################

### Npcs Index
GET {{host}}/npcs.json

### Npcs Create
POST {{host}}/npcs.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "Boblin",
  "race": "humanoid",
  "api_class": "Goblin",
  "alignment": "neutral evil",
  "level": "4",
  "campaign_id": "2"
}

### Npcs Show
GET {{host}}/npcs/4.json

### Npcs Update
PATCH {{host}}/npcs/4.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "Jimothy",
  "race": "human",
  "api_class": "fighter",
  "alignment": "chaotic good"
}

### Npcs Destroy
DELETE {{host}}/npcs/5.json
Authorization: Bearer {{jwt}}


#################### USERS ######################

### Users create (signup)
POST {{host}}/users.json
Content-Type: application/json

{
  "username": "disconerds",
  "email": "disconerds@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST {{host}}/sessions.json
Content-Type: application/json

{
  "email": "disconerds@gmail.com",
  "password": "password"
}